curr_dir=`realpath $(dirname $0)`
args=""
args+=" -L /share/qemu"
args+=" -machine q35,accel=kvm,kernel_irqchip=split"
args+=" -cpu host,-vmx-rdseed-exit,pmu=off"
args+=" -m 512G"
args+=" -smp 64"
args+=" -boot menu=on"
args+=" -bios /usr/share/ovmf/OVMF.fd"
args+=" -device virtio-blk-pci,drive=demo-image"
args+=" -drive id=demo-image,file=${curr_dir}/demo.raw,format=raw,if=none"
args+=" -device vhost-vsock-pci,guest-cid=8022"
# args+=" -object tdx-guest,sept-ve-disable=on,id=tdx,quote-generation-service=vsock:2:4050"
# args+=" -object memory-backend-memfd-private,id=dimm1,size=256G"
# args+=" -machine confidential-guest-support=tdx,memory-backend=dimm1"
# append="rootwait rootflags=data=ordered,errors=remount-ro rw root=/dev/vda1 rootfstype=ext4 console=ttyS0 console=tty0 tdx_disable_filter systemd.show_status=true systemd.log_level=debug net.ifnames=0"
args+=" -device virtio-net-pci,netdev=mynet0,mac=7a:4a:fd:3a:0c:d2"
args+=" -netdev user,id=mynet0,hostfwd=tcp::8023-:22"
args+=" -vga none"
args+=" -nographic -serial mon:stdio"
args+=" -monitor tcp:127.0.0.1:4444,server,nowait"
args+=" -device virtio-serial-pci"
qemu-system-x86_64 ${args} -append "${append}"